on:
  workflow_dispatch:
  schedule:
  - cron: "0 5 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:4.2
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Calculate and QAQC fluxes
        run: |
          R -e 'utils::install.packages("here")'
          Rscript ./R/generate_L1_fluxes.R
        
      - name: Commit and push
        run: |
          git config --global user.name 'abbylewis'
          git commit -am "Automated update"
          git push
